# Generated by Django 4.2.5 on 2024-01-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelDataModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExcelDataModel',
            new_name='questions',
        ),
    ]
