# Generated by Django 4.2.5 on 2024-01-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelDataModel', '0003_question_delete_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
