# Generated by Django 4.2.5 on 2024-01-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelDataModel', '0006_subject_chapter_subject_question_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='short_question',
        ),
        migrations.AddField(
            model_name='question',
            name='long_question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
