# Generated by Django 4.2.5 on 2024-01-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExcelDataModel', '0008_question_question_type_alter_question_short_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='numerical_question',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('short', 'Short Question'), ('long', 'Long Question'), ('numerical', 'Numerical Question')], default='short', max_length=10),
        ),
    ]
